### PR TITLE
authentication does not work

### PR DESCRIPTION
**Pull request by surr-name**
it should fix it

### CODE REVIEW

**Comment by diversario** [comment]
Sorry! I did not receive a notification about this PR :/

**Comment by JonnyBGod** [comment]
This just broke everything...
Why switching to admin() database?
This makes no sense at all, this library does not need to authenticate to admin database as it is not intended to manage the database.

Please revert this commit.
-1

**Comment by diversario** [comment]
Please stick with v0.0.11 while I investigate.
What broke for you?

**Comment by diversario** [comment]
@surr-name I'm reverting this commit (sorry for rushingly accepting it); can you provide some details about what wasn't working for you before you made this change?

**Comment by surr-name** [comment]
It was my dull mistake, I've not properly investigated the problem. I am really sorry for it!

**Pull request merged**
